# Generated by Django 5.0.1 on 2025-05-07 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaap', '0002_jaapentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityJaapCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'City Jaap Count',
                'verbose_name_plural': 'City Jaap Counts',
                'ordering': ['-date', 'city'],
                'unique_together': {('city', 'date')},
            },
        ),
    ]
