# Generated by Django 5.0.1 on 2025-04-12 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('count', 'Count Milestone'), ('streak', 'Streak Milestone'), ('daily', 'Daily Target'), ('weekly', 'Weekly Target'), ('monthly', 'Monthly Target'), ('yearly', 'Yearly Target'), ('special', 'Special Achievement')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.PositiveIntegerField(default=108)),
                ('weekly_target', models.PositiveIntegerField(default=756)),
                ('monthly_target', models.PositiveIntegerField(default=3240)),
                ('yearly_target', models.PositiveIntegerField(default=39420)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
